### ISSUE TITLE
Allow user to choose the version of CAPEC / ATT&CK being used

### ISSUE THREAD

**Issue by himynamesdave** [signalscorps/file2stix#101]
ATT&CK have just released v12: https://medium.com/mitre-attack/introducing-attack-campaigns-6b15baa6cbb4

By default we should always support the latest version of ATT&CK when user updates Mitre database cache.

This can be done using release tags,

https://github.com/mitre/cti/releases

e.g.

* https://github.com/mitre/cti/tree/ATT%26CK-v12.0
* https://github.com/mitre/cti/tree/ATT%26CK-v11.3
* ...

If user wants to use a specific ATT&CK version then can specify the branch name e.g. `--mitre-attack-version ATT%26CK-v11.3`

If not supplied, the default will be used (latest tag).

CAPEC does not work in the same way, so we should always use the latest version

**Comment by himynamesdave** [comment]
@shanthanu9 can you explain how this can be tested? I can't see anything that allows me to pass ATT&CK or CAPEC version.

**Comment by himynamesdave** [comment]
Thanks @shanthanu9 but appears to not be working.

No extraction, as subtechnique not present in version:

```shell
file2stix --input-file tests/observable_tests/mitre_attck_enterprise-v12-technique.txt --update-mitre-cti-database --mitre-attack-version ATT%26CK-v7.0
```

Extraction, as subtechnique not present in version:


```shell
file2stix --input-file tests/observable_tests/mitre_attck_enterprise-v12-technique.txt --update-mitre-cti-database --mitre-attack-version ATT%26CK-v12.1
```

You can check this by downloading the zips of each version (here https://github.com/mitre/cti/tags) and searching on the match string (T1583.007). It is only present in the v12 code

**Comment by himynamesdave** [comment]
@shanthanu9 understood

Now see this error (perhaps because no matches to this version? v12 works, where match does exist)

```
 file2stix --input-file tests/observable_tests/mitre_attck_enterprise-v12-technique.txt --update-mitre-cti-database --mitre-attack-version "ATT&CK-v7.0"
[2022-12-05 12:07:30,973] INFO: Pulling latest changes from https://github.com/mitre/cti
[2022-12-05 12:07:35,538] INFO: Reading input file /Users/dgreenwood/Documents/repos/signalscorps/file2stix/tests/observable_tests/mitre_attck_enterprise-v12-technique.txt ...
[2022-12-05 12:07:35,539] INFO: Extracted all observables of type ipv4
[2022-12-05 12:07:35,539] INFO: Extracted all observables of type ipv4-with-port
[2022-12-05 12:07:35,539] INFO: Extracted all observables of type ipv6
[2022-12-05 12:07:35,540] INFO: Extracted all observables of type ipv6-with-port
[2022-12-05 12:07:35,540] INFO: Extracted all observables of type User Agent
[2022-12-05 12:07:35,541] INFO: Extracted all observables of type File name
[2022-12-05 12:07:35,541] INFO: Extracted all observables of type md5
[2022-12-05 12:07:35,541] INFO: Extracted all observables of type sha1
[2022-12-05 12:07:35,541] INFO: Extracted all observables of type sha256
[2022-12-05 12:07:35,541] INFO: Extracted all observables of type sha512
[2022-12-05 12:07:35,541] INFO: Extracted all observables of type ssdeep
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type Directory
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type Domain
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type URL
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type Email Address
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type MAC Address
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type Windows Registry Key
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type AS
[2022-12-05 12:07:35,542] INFO: Extracted all observables of type BTC
[2022-12-05 12:07:35,543] INFO: Extracted all observables of type ETH
[2022-12-05 12:07:35,543] INFO: Extracted all observables of type XMR
[2022-12-05 12:07:35,543] INFO: Extracted all observables of type CVE
[2022-12-05 12:07:35,548] INFO: Extracted all observables of type Country Name
[2022-12-05 12:07:35,551] INFO: Extracted all observables of type Country Code Alpha 2
[2022-12-05 12:07:35,554] INFO: Extracted all observables of type Country Code Alpha 3
[2022-12-05 12:07:35,554] INFO: Extracted all observables of type Mastercard Credit Card
[2022-12-05 12:07:35,554] INFO: Extracted all observables of type VISA Credit Card
[2022-12-05 12:07:35,554] INFO: Extracted all observables of type Amex Credit Card
[2022-12-05 12:07:35,554] INFO: Extracted all observables of type Union Pay Credit Card
[2022-12-05 12:07:35,554] INFO: Extracted all observables of type Diners Credit Card
[2022-12-05 12:07:35,555] INFO: Extracted all observables of type JCB Credit Card
[2022-12-05 12:07:35,555] INFO: Extracted all observables of type IBAN
[2022-12-05 12:07:35,555] INFO: Extracted all observables of type YARA Rule
[2022-12-05 12:07:35,555] INFO: Extracted all observables of type CPE
[2022-12-05 12:07:35,555] INFO: Extracted all observables of type SIGMA Rule
[2022-12-05 12:07:36,902] INFO: Extracted all observables of type MITRE Enterprise ATT&CK
[2022-12-05 12:07:36,902] INFO: Custom extraction file not given, hence not extracting any custom observables.
[2022-12-05 12:07:36,902] INFO: Extracted all observables of type Custom Observable
[2022-12-05 12:07:36,902] INFO: Extracted all observables of type Custom Observable
[2022-12-05 12:07:37,037] INFO: Extracted all observables of type MITRE Mobile ATT&CK
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/bin/file2stix", line 8, in <module>
    sys.exit(cli())
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix/cli.py", line 246, in cli
    main(config)
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix/main.py", line 173, in main
    for stix_observable_objects in ExtractStixObservables(
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix/extract_observables.py", line 52, in __init__
    observable_cls.build_extraction_regex(cache.cti_folder_path)
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix/observables.py", line 1085, in build_extraction_regex
    super().build_extraction_regex(cti_folder, bundle_relative_path)
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix/observables.py", line 998, in build_extraction_regex
    cls.memory_store.load_from_file(f"{cti_folder}/{bundle_relative_path}")
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.10/site-packages/stix2/datastore/memory.py", line 148, in load_from_file
    return self.source.load_from_file(*args, **kwargs)
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.10/site-packages/stix2/datastore/memory.py", line 363, in load_from_file
    with io.open(os.path.abspath(file_path), "r", encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix-cache/cti/ics-attack/ics-attack.json'
```

**Comment by himynamesdave** [comment]
PASS

```
file2stix --input-file tests/observable_tests/mitre_attck_enterprise-v12-not-v7-technique.txt --update-mitre-cti-database --mitre-attack-version "ATT&CK-v7.0"
```

PASS

```
file2stix --input-file tests/observable_tests/mitre_attck_enterprise-v12-not-v7-technique.txt --update-mitre-cti-database --mitre-attack-version "ATT&CK-v12.1"
```

PASS
