### ISSUE TITLE
Add support for ATT&CK ICS

### ISSUE THREAD

**Issue by himynamesdave** [signalscorps/file2stix#25]
Currently support Mobile and Enterprise.

SHould also include ICS: https://github.com/mitre/cti/tree/master/ics-attack

**Comment by himynamesdave** [comment]
@shanthanu9 I am getting errors with ATT&CK extractions. to recreate

```
file2stix --input-file tests/observable_tests/mitre_attck.txt
```

see

```
Traceback (most recent call last):
  File "/file2stix_venv/bin/file2stix", line 10, in <module>
    sys.exit(cli())
  File "/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/cli.py", line 77, in cli
    main(config)
  File "/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/main.py", line 138, in main
    stix_observables[stix_observable_object.name] = stix_observable_object
AttributeError: 'dict' object has no attribute 'name'
```
