### ISSUE TITLE
For identity and extension-definition objects use central repo

### ISSUE THREAD

**Issue by himynamesdave** [signalscorps/file2stix#51]
I want to modularise the default values.

As such I have created a central repo with default identity and extension definitions that should be imported (and updatable) in file2stix available here:

https://github.com/signalscorps/stix2-objects

**Comment by himynamesdave** [comment]
that approach sounds goof to me @shanthanu9

**Comment by himynamesdave** [comment]
I think the identity default object is failing. When I run a command the needs an identity file (the default, because custom not specified) the script throws an error:

```
file2stix --input-file tests/custom_warning_lists/list.json --tlp-level GREEN 
[2022-09-21 20:17:55,355] INFO: Reading input file /Users/dgreenwood/Documents/repos/signalscorps/file2stix/tests/custom_warning_lists/list.json ...
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/bin/file2stix", line 8, in <module>
    sys.exit(cli())
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/cli.py", line 229, in cli
    main(config)
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/main.py", line 162, in main
    identity_id = extracted_stix_observable.identity.id
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.9/site-packages/stix2/base.py", line 269, in __getattr__
    raise AttributeError(
AttributeError: 'Indicator' object has no attribute 'identity'
```
