### ISSUE TITLE
Unclear what --output-json-file does

### ISSUE THREAD

**Issue by himynamesdave** [signalscorps/file2stix#74]

**Comment by himynamesdave** [comment]
@shanthanu9 I assume it is not possible to change the `stix2-objects` directory right? If correct, this is what I want -- just want to confirm

**Comment by himynamesdave** [comment]
@shanthanu9 not quite,

```
file2stix --input-file tests/observable_tests/ipv4.txt --output-json-file stix2_bundles_alt
```

Even when directory exists (I created manually), this command fails;

```
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/bin/file2stix", line 8, in <module>
    sys.exit(cli())
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/cli.py", line 231, in cli
    main(config)
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/main.py", line 451, in main
    stix_bundle_file_path = stix_store.store_objects_in_bundle(
  File "/Users/dgreenwood/Documents/repos/signalscorps/file2stix/file2stix_venv/lib/python3.9/site-packages/file2stix/observables_stix_store.py", line 124, in store_objects_in_bundle
    with open(stix_bundle_file, "w") as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/dgreenwood/Documents/repos/signalscorps/file2stix/stix2_bundles_alt'
```
